/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OperadorRouteImport } from './routes/operador'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OperadorIndexRouteImport } from './routes/operador.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as OperadorRetiradaRouteImport } from './routes/operador.retirada'
import { Route as OperadorHistoricoRouteImport } from './routes/operador.historico'
import { Route as OperadorEntradaRouteImport } from './routes/operador.entrada'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminRetiradaRouteImport } from './routes/admin.retirada'
import { Route as AdminProdutosRouteImport } from './routes/admin.produtos'
import { Route as AdminMovimentacoesRouteImport } from './routes/admin.movimentacoes'
import { Route as AdminInventarioRouteImport } from './routes/admin.inventario'
import { Route as AdminEntradaRouteImport } from './routes/admin.entrada'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'

const OperadorRoute = OperadorRouteImport.update({
  id: '/operador',
  path: '/operador',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadorIndexRoute = OperadorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OperadorRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const OperadorRetiradaRoute = OperadorRetiradaRouteImport.update({
  id: '/retirada',
  path: '/retirada',
  getParentRoute: () => OperadorRoute,
} as any)
const OperadorHistoricoRoute = OperadorHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => OperadorRoute,
} as any)
const OperadorEntradaRoute = OperadorEntradaRouteImport.update({
  id: '/entrada',
  path: '/entrada',
  getParentRoute: () => OperadorRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRetiradaRoute = AdminRetiradaRouteImport.update({
  id: '/retirada',
  path: '/retirada',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMovimentacoesRoute = AdminMovimentacoesRouteImport.update({
  id: '/movimentacoes',
  path: '/movimentacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventarioRoute = AdminInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEntradaRoute = AdminEntradaRouteImport.update({
  id: '/entrada',
  path: '/entrada',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/operador': typeof OperadorRouteWithChildren
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/entrada': typeof AdminEntradaRoute
  '/admin/inventario': typeof AdminInventarioRoute
  '/admin/movimentacoes': typeof AdminMovimentacoesRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/retirada': typeof AdminRetiradaRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/operador/entrada': typeof OperadorEntradaRoute
  '/operador/historico': typeof OperadorHistoricoRoute
  '/operador/retirada': typeof OperadorRetiradaRoute
  '/admin/': typeof AdminIndexRoute
  '/operador/': typeof OperadorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/entrada': typeof AdminEntradaRoute
  '/admin/inventario': typeof AdminInventarioRoute
  '/admin/movimentacoes': typeof AdminMovimentacoesRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/retirada': typeof AdminRetiradaRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/operador/entrada': typeof OperadorEntradaRoute
  '/operador/historico': typeof OperadorHistoricoRoute
  '/operador/retirada': typeof OperadorRetiradaRoute
  '/admin': typeof AdminIndexRoute
  '/operador': typeof OperadorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/operador': typeof OperadorRouteWithChildren
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/entrada': typeof AdminEntradaRoute
  '/admin/inventario': typeof AdminInventarioRoute
  '/admin/movimentacoes': typeof AdminMovimentacoesRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/retirada': typeof AdminRetiradaRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/operador/entrada': typeof OperadorEntradaRoute
  '/operador/historico': typeof OperadorHistoricoRoute
  '/operador/retirada': typeof OperadorRetiradaRoute
  '/admin/': typeof AdminIndexRoute
  '/operador/': typeof OperadorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/operador'
    | '/admin/configuracoes'
    | '/admin/entrada'
    | '/admin/inventario'
    | '/admin/movimentacoes'
    | '/admin/produtos'
    | '/admin/retirada'
    | '/admin/usuarios'
    | '/operador/entrada'
    | '/operador/historico'
    | '/operador/retirada'
    | '/admin/'
    | '/operador/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/configuracoes'
    | '/admin/entrada'
    | '/admin/inventario'
    | '/admin/movimentacoes'
    | '/admin/produtos'
    | '/admin/retirada'
    | '/admin/usuarios'
    | '/operador/entrada'
    | '/operador/historico'
    | '/operador/retirada'
    | '/admin'
    | '/operador'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/operador'
    | '/admin/configuracoes'
    | '/admin/entrada'
    | '/admin/inventario'
    | '/admin/movimentacoes'
    | '/admin/produtos'
    | '/admin/retirada'
    | '/admin/usuarios'
    | '/operador/entrada'
    | '/operador/historico'
    | '/operador/retirada'
    | '/admin/'
    | '/operador/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  OperadorRoute: typeof OperadorRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/operador': {
      id: '/operador'
      path: '/operador'
      fullPath: '/operador'
      preLoaderRoute: typeof OperadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operador/': {
      id: '/operador/'
      path: '/'
      fullPath: '/operador/'
      preLoaderRoute: typeof OperadorIndexRouteImport
      parentRoute: typeof OperadorRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/operador/retirada': {
      id: '/operador/retirada'
      path: '/retirada'
      fullPath: '/operador/retirada'
      preLoaderRoute: typeof OperadorRetiradaRouteImport
      parentRoute: typeof OperadorRoute
    }
    '/operador/historico': {
      id: '/operador/historico'
      path: '/historico'
      fullPath: '/operador/historico'
      preLoaderRoute: typeof OperadorHistoricoRouteImport
      parentRoute: typeof OperadorRoute
    }
    '/operador/entrada': {
      id: '/operador/entrada'
      path: '/entrada'
      fullPath: '/operador/entrada'
      preLoaderRoute: typeof OperadorEntradaRouteImport
      parentRoute: typeof OperadorRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/retirada': {
      id: '/admin/retirada'
      path: '/retirada'
      fullPath: '/admin/retirada'
      preLoaderRoute: typeof AdminRetiradaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/movimentacoes': {
      id: '/admin/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/admin/movimentacoes'
      preLoaderRoute: typeof AdminMovimentacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventario': {
      id: '/admin/inventario'
      path: '/inventario'
      fullPath: '/admin/inventario'
      preLoaderRoute: typeof AdminInventarioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/entrada': {
      id: '/admin/entrada'
      path: '/entrada'
      fullPath: '/admin/entrada'
      preLoaderRoute: typeof AdminEntradaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminEntradaRoute: typeof AdminEntradaRoute
  AdminInventarioRoute: typeof AdminInventarioRoute
  AdminMovimentacoesRoute: typeof AdminMovimentacoesRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminRetiradaRoute: typeof AdminRetiradaRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminEntradaRoute: AdminEntradaRoute,
  AdminInventarioRoute: AdminInventarioRoute,
  AdminMovimentacoesRoute: AdminMovimentacoesRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminRetiradaRoute: AdminRetiradaRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface OperadorRouteChildren {
  OperadorEntradaRoute: typeof OperadorEntradaRoute
  OperadorHistoricoRoute: typeof OperadorHistoricoRoute
  OperadorRetiradaRoute: typeof OperadorRetiradaRoute
  OperadorIndexRoute: typeof OperadorIndexRoute
}

const OperadorRouteChildren: OperadorRouteChildren = {
  OperadorEntradaRoute: OperadorEntradaRoute,
  OperadorHistoricoRoute: OperadorHistoricoRoute,
  OperadorRetiradaRoute: OperadorRetiradaRoute,
  OperadorIndexRoute: OperadorIndexRoute,
}

const OperadorRouteWithChildren = OperadorRoute._addFileChildren(
  OperadorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  OperadorRoute: OperadorRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
